#!/usr/bin/env bash

if [ -n "${__bash_doc_included__}" ]; then return 0; fi
export __bash_doc_included__=true

if [ -z "${BASH_DOC_DIR}" ]; then
    BASH_DOC_DIR="$(dirname $(readlink -f $0))"
fi

echo "BASH_DOC_DIR: $BASH_DOC_DIR"

# ===================== > Source and export functions < ====================== #
source ${BASH_DOC_DIR}/functions/init_functions.sh
source ${BASH_DOC_DIR}/functions/format_functions.sh
source ${BASH_DOC_DIR}/functions/aux.sh
source ${BASH_DOC_DIR}/functions/need_help.sh
source ${BASH_DOC_DIR}/functions/parse_arguments.sh
source ${BASH_DOC_DIR}/functions/show_functions.sh
# ────────────────────────────────── <end> ─────────────────────────────────── #
# ========================= > Export all functions < ========================= #
eval "$(declare -F | sed -e 's/-f /-fx /')"
# ────────────────────────────────── <end> ─────────────────────────────────── #
