#!/usr/bin/env bash

pkg_name="bash_doc"

pkg_includeguard="__${pkg_name}_included__"
pkg_dir="__${pkg_name}_dir__"

if [ -n "${!pkg_includeguard}" ]; then return 0; fi
export ${pkg_includeguard}=true

if [ -z "${!pkg_dir}" ]; then
    current_file=
    if [ -n "$BASH_VERSION" ]; then
        current_file="${BASH_SOURCE[-1]}"
    elif [ -n "$ZSH_VERSION" ]; then
        current_file="${(%):-%N}"
    fi
    declare ${pkg_dir}="$(dirname $(readlink -f "${current_file}"))"
fi

echo "BASH_DOC_DIR: ${!pkg_dir}"

# ===================== > Source and export functions < ====================== #
source ${!pkg_dir}/functions/err
source ${!pkg_dir}/functions/format_functions
source ${!pkg_dir}/functions/format_help
source ${!pkg_dir}/functions/indent
source ${!pkg_dir}/functions/init_functions
source ${!pkg_dir}/functions/max
source ${!pkg_dir}/functions/need_help
source ${!pkg_dir}/functions/newline
source ${!pkg_dir}/functions/parse_arguments
source ${!pkg_dir}/functions/rep
source ${!pkg_dir}/functions/show_help
# ────────────────────────────────── <end> ─────────────────────────────────── #
# # ========================= > Export all functions < ========================= #
# eval "$(declare -F |
#     perl -p0e "s/declare\s+-f\s+(.*)\s*$/export -f \${1}/gmi")"
# # ────────────────────────────────── <end> ─────────────────────────────────── #

