#!/usr/bin/env bash

if [ -n "${__bash_doc_included__}" ]; then return 0; fi
export __bash_doc_included__=true

if [ -z "${BASH_DOC_DIR}" ]; then
    if [ -n "$BASH_VERSION" ]; then
        current_file="${BASH_SOURCE[0]}"
    elif [ -n "$ZSH_VERSION" ]; then
        current_file="${(%):-%N}"
    fi
    BASH_DOC_DIR="$(dirname $(readlink -f "${current_file}"))"
fi

echo "BASH_DOC_DIR: $BASH_DOC_DIR"

# ===================== > Source and export functions < ====================== #
source ${BASH_DOC_DIR}/functions/err
source ${BASH_DOC_DIR}/functions/format_functions
source ${BASH_DOC_DIR}/functions/format_help
source ${BASH_DOC_DIR}/functions/indent
source ${BASH_DOC_DIR}/functions/init_functions
source ${BASH_DOC_DIR}/functions/max
source ${BASH_DOC_DIR}/functions/need_help
source ${BASH_DOC_DIR}/functions/newline
source ${BASH_DOC_DIR}/functions/parse_arguments
source ${BASH_DOC_DIR}/functions/rep
source ${BASH_DOC_DIR}/functions/show_help
# ────────────────────────────────── <end> ─────────────────────────────────── #
# ========================= > Export all functions < ========================= #
eval "$(declare -F | sed -e 's/-f /-fx /')"
# ────────────────────────────────── <end> ─────────────────────────────────── #
