---
title: bash-doc
output:
  md_document:
    variant: markdown_github
---



Simple functions for creating and formating documentation of bash scripts / functions

### Create documentation

#### `init_doc`

Initialize the documentation block

**Arguments:**
none

#### `init_desc`

Set the description of the function / script

**Arguments:**

- `$1,...,$n`: Lines of the description

#### `init_arg`

Initialize named arguments to be set via `--arg=val` or `--arg val` (using one or two dashes)

**Arguments:**
- `$1`: Argument type  
- `$2`: Argument name
- `$3`: Argument description
- `$4`: Default value

### Set arguments

#### `parse_arguments`
Set arguments passed as `--arg=val` or `--arg val` (using one or two dashes).
Should be used as `eval "$(parse_arguments "$@")"`

**Arguments:**
- `$1,...,$n`: Arguments to be set.

    
### Print help

#### `need_help`

Show the help if argument `-h` or `-help` (using one or two dashes) is present. If output is console and tput is available, tput is used for colouring.

**Arguments:**
none

## Examples

The following function is a basic example of how to use `bash-doc`:



```{bash example_function, engine.opts="-l",echo=FALSE,comment=NA,class.output="bash"}
cat "examples/example_function.sh"
source "examples/example_function.sh"
```

### Printing help

```{bash example_help_show, engine.opts="-l",echo=FALSE,comment=NA,class.output="bash"}
cat "examples/example_help.sh"
```

```{bash example_help,echo=FALSE,comment=NA}
source "examples/example_function.sh"
export TERM="dumb"
source "examples/example_help.sh"
```

### Setting arguments

Defaults are used if an argument is not specified:

```{bash example_int_only_show, engine.opts="-l",echo=FALSE,comment=NA,class.output="bash"}
cat "examples/example_int_only.sh"
```

```{bash example_int_only,echo=FALSE,comment=NA}
source "examples/example_function.sh"
source "examples/example_int_only.sh"
```

```{bash example_str_only_show, engine.opts="-l",echo=FALSE,comment=NA,class.output="bash"}
cat "examples/example_str_only.sh"
```

```{bash example_str_only,echo=FALSE,comment=NA}
source "examples/example_function.sh"
source "examples/example_str_only.sh"
```

but setting an argument overwrites the defaults:

```{bash example_int_and_str_show, engine.opts="-l",echo=FALSE,comment=NA,class.output="bash"}
cat "examples/example_int_and_str.sh"
```

```{bash example_int_and_str,echo=FALSE,comment=NA}
source "examples/example_function.sh"
source "examples/example_int_and_str.sh"
```



